ALTER TABLE books ADD COLUMN plex_rating_key TEXT NOT NULL DEFAULT '';
ALTER TABLE books ADD COLUMN plex_title TEXT NOT NULL DEFAULT '';
ALTER TABLE books ADD COLUMN media_server_id TEXT NOT NULL DEFAULT '';
ALTER TABLE books ADD COLUMN media_server_title TEXT NOT NULL DEFAULT '';
